### ISSUE TITLE
Vote for your post and comments

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#112] opened 2019-01-08 22:05 UTC
You can vote for your posts and comments. I think that this bug maybe perturb economy satoshi and reputation. Vote for your post should be blocked. This is a critical bug.

**Comment by Horndev** [comment] 2019-01-09 20:07
Yes, you can vote for your own post.  This is by design.

- 60% of your vote goes back into your own wallet.
- 30% goes to other users
- 10% goes to zapread operations costs.

Ideally, I would like to have 0% go back to own wallet, but this is impossible to implement because anonymous voting is possible (vote without logging in via invoice).

Think of voting for your own post as paying for advertising.  Except - that the payment goes to the website users instead of just the website owner.

If the 60% income proportion is too high, I may reduce it in the future.  I still have to do some Math / game theory to see what the Nash Equilibrium is for this.

Maybe 50/20/20/10 could be better?

**Comment by Horndev** [comment] 2019-01-09 20:07
I should add a discussion on this in the FAQ section.  Do you have any other comments about this?  I would like to make sure to capture any concerns in the FAQ update.

**Comment by fervi** [comment] 2019-01-09 21:33
This make sense, but self voting shouldn't increate reputation (and maybe in-voice paying)

**Comment by Horndev** [comment] 2019-01-10 02:06
It's hard to block reputation increase too - since a user can just log out and vote anonymously.

**Comment by Horndev** [comment] 2019-01-11 14:35
Ok, I'm going to address the reputation change in this way:

- Only votes from logged in users, and not for yourself will change reputation.

https://github.com/Horndev/zapread.com/issues/124

**Comment by DocBox12** [comment] 2019-01-11 15:20
Ok, this is a good idea.

**Comment by Horndev** [comment] 2019-01-12 18:52
Now that I changed the reputation system, I'm going to close this discussion.
The next change will be to implement weighted reputation updates.  

- Anonymous votes only apply 50% change to score
- Poor reputation reduces change to score/reputation

This is captured in this issue: https://github.com/Horndev/zapread.com/issues/104

**Closed by Horndev** 2019-01-12 18:52 UTC
Labels: Discussion
